#!/bin/sh
ECHO=`which echo`
BUILDDIR="../../build"
FIRST_TIME=0
cd layers/openembedded-core/
if [ ! -f ${BUILDDIR}/conf/local.conf ]; then
	FIRST_TIME=1
fi

. ./oe-init-build-env ${BUILDDIR}

echo ""
echo "ISOBlue targets are:"
echo "    console-isoblue-image"

if [ $FIRST_TIME -eq 1 ]; then
	mkdir -p conf
	cp ../layers/meta-isoblue-demos/buildconf/*.conf conf/

	echo ""
fi
